// jtag_microgpt_bridge.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module jtag_microgpt_bridge (
		input  wire        clk_clk,              //    clk.clk
		output wire [31:0] master_address,       // master.address
		input  wire [31:0] master_readdata,      //       .readdata
		output wire        master_read,          //       .read
		output wire        master_write,         //       .write
		output wire [31:0] master_writedata,     //       .writedata
		input  wire        master_waitrequest,   //       .waitrequest
		input  wire        master_readdatavalid, //       .readdatavalid
		output wire [3:0]  master_byteenable,    //       .byteenable
		input  wire        reset_reset_n         //  reset.reset_n
	);

	jtag_microgpt_bridge_jtag_master #(
		.USE_PLI     (0),
		.PLI_PORT    (50000),
		.FIFO_DEPTHS (8)
	) jtag_master (
		.clk_clk              (clk_clk),              //          clk.clk
		.clk_reset_reset      (~reset_reset_n),       //    clk_reset.reset
		.master_address       (master_address),       //       master.address
		.master_readdata      (master_readdata),      //             .readdata
		.master_read          (master_read),          //             .read
		.master_write         (master_write),         //             .write
		.master_writedata     (master_writedata),     //             .writedata
		.master_waitrequest   (master_waitrequest),   //             .waitrequest
		.master_readdatavalid (master_readdatavalid), //             .readdatavalid
		.master_byteenable    (master_byteenable),    //             .byteenable
		.master_reset_reset   ()                      // master_reset.reset
	);

endmodule
