+incdir+code/rtl/config
+incdir+code/rtl/transformer_my/talos_reuse/include
code/rtl/transformer_my/primitive/fp16/floatAdd16.v
code/rtl/transformer_my/primitive/fp16/floatMult16.v
code/rtl/transformer_my/primitive/fp16/processingElement16.v
code/rtl/transformer_my/primitive/fp32/floatAdd.v
code/rtl/transformer_my/primitive/fp32/floatMult.v
code/rtl/transformer_my/primitive/fp32/processingElement.v
code/rtl/transformer_my/primitive/projection_templates/convUnit.v
code/rtl/transformer_my/primitive/projection_templates/layer.v
code/rtl/transformer_my/primitive/numeric_templates/exponent.v
code/rtl/transformer_my/primitive/numeric_templates/floatReciprocal.v
code/rtl/transformer_my/primitive/numeric_templates/softmax_1.v
code/rtl/transformer_my/primitive/numeric_templates/softmax_2.v
code/rtl/transformer_my/primitive/numeric_templates/softmax.v
code/rtl/transformer_my/talos_reuse/processing_element.sv
code/rtl/transformer_my/talos_reuse/systolic_matvec16_tile.sv
code/rtl/transformer_my/talos_reuse/matrixmul_unit.sv
code/rtl/transformer_my/talos_reuse/rms_scale_engine.sv
code/rtl/transformer_my/talos_reuse/sat_div16_engine.sv
code/rtl/transformer_my/talos_reuse/microgpt_categorical_sampler.sv
