from math import cos, pi, sin
from pathlib import Path
import struct


LUT_SIZE = 1024
ROPE_THETA = 1_000_000.0
HEAD_DIM = 128
PAIR_COUNT = HEAD_DIM // 2


def fp16_hex(value: float) -> str:
    return f"16'h{struct.pack('>e', float(value)).hex()}"


def q16_hex(value: float) -> str:
    scaled = int(round(value * (1 << 16))) & 0xFFFFFFFF
    return f"32'h{scaled:08x}"


def main() -> None:
    repo_root = Path(__file__).resolve().parents[2]
    out_path = repo_root / "code" / "rtl" / "transformer" / "fp16_rope_tables.vh"
    lines = []
    lines.append("// Auto-generated by code/script/gen_rope_tables.py")
    lines.append("// RoPE phase-step table uses Q16.16 LUT phase units.")
    lines.append("")

    for pair_idx in range(PAIR_COUNT):
        freq = 1.0 / (ROPE_THETA ** (2.0 * pair_idx / HEAD_DIM))
        phase_step = freq * LUT_SIZE / (2.0 * pi)
        lines.append(f"if (PAIR_COUNT > {pair_idx}) freq_table_q16[{pair_idx}] = {q16_hex(phase_step)};")

    lines.append("")

    for lut_idx in range(LUT_SIZE):
        angle = (2.0 * pi * lut_idx) / LUT_SIZE
        lines.append(f"cos_table[{lut_idx}] = {fp16_hex(cos(angle))};")

    lines.append("")

    for lut_idx in range(LUT_SIZE):
        angle = (2.0 * pi * lut_idx) / LUT_SIZE
        lines.append(f"sin_table[{lut_idx}] = {fp16_hex(sin(angle))};")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(out_path)


if __name__ == "__main__":
    main()
